/**
 * [project-name]
 * next-feature@0.1.1-beta.3
 * December 31st 2025, 3:30:54 pm
 */
export const PROJECT_NAME = "EduPulse";

/**
 * [project-description]
 * next-feature@0.1.1-beta.3
 * December 31st 2025, 3:32:22 pm
 */
export const PROJECT_DESCRIPTION = 'Generated by @dcat23/next-feature';
